# Site Info
site_name: Cisneros Research Tutorials
site_url: https://cisnerosresearch.github.io/docs
site_description: |
  A place for the Cisneros group to document tutorials and code.

# GitHub Repository
repo_name: CisnerosResearch/docs
repo_url: https://github.com/CisnerosResearch/docs
edit_uri: edit/main/docs/

# Set for GitHub Pages
docs_dir: base
site_dir: docs

# Copyright
copyright: |
  Copyright &copy; 2022 <a href="http://cisnerosres.utdallas.edu/"  target="_blank" rel="noopener">Cisneros Research Group</a>

# Specify social media logos/links
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/CisnerosResearch
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/CisnerosRes
    - icon: fontawesome/solid/info-circle
      link: http://cisnerosres.utdallas.edu/

# Set up theme
theme:
  language: en
  name: material
  icon:
     repo: material/git
     logo: material/dna
  # Assumes within base/ directory
  # logo: assets/CRG-color.png
  features:
    # Keep tags in header
    - navigation.tabs
    - navigation.tabs.sticky
    # Add "back to top" button
    - navigation.top
    # Update link location on page when scrolling
    - navigation.tracking
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: light-utd
      toggle:
        #icon: material/toggle-switch-off-outline
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: dark-utd
      toggle:
        #icon: material/toggle-switch
        icon: material/weather-sunny
        name: Switch to light mode

# Extensions
markdown_extensions:
  # Necessary for Font Awesome
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  # Add admonition/callouts
  - admonition
  - pymdownx.details
  - pymdownx.superfences

# Plugins
plugins:
  - search
  - git-revision-date

# Change colors to meet web accessibility
extra_css:
  - assets/stylesheets/extra.css

# Page Tree
nav:
   - Home: index.md
   - LICHEM:
      - lichem/index.md
   - AMBER:
      - amber/index.md
      - PyRED Tutorial: amber/pyred-tut.md
